"""empty message

Revision ID: 912918f30de6
Revises: 
Create Date: 2019-10-29 17:13:00.105706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912918f30de6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_index(op.f('ix_admin_role'), 'admin', ['role'], unique=True)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('loader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loader_email'), 'loader', ['email'], unique=True)
    op.create_index(op.f('ix_loader_role'), 'loader', ['role'], unique=True)
    op.create_index(op.f('ix_loader_username'), 'loader', ['username'], unique=True)
    op.create_table('recepient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepient_email'), 'recepient', ['email'], unique=True)
    op.create_index(op.f('ix_recepient_role'), 'recepient', ['role'], unique=True)
    op.create_index(op.f('ix_recepient_username'), 'recepient', ['username'], unique=True)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_email'), 'supplier', ['email'], unique=True)
    op.create_index(op.f('ix_supplier_role'), 'supplier', ['role'], unique=True)
    op.create_index(op.f('ix_supplier_username'), 'supplier', ['username'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_supplier_username'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_role'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_email'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_recepient_username'), table_name='recepient')
    op.drop_index(op.f('ix_recepient_role'), table_name='recepient')
    op.drop_index(op.f('ix_recepient_email'), table_name='recepient')
    op.drop_table('recepient')
    op.drop_index(op.f('ix_loader_username'), table_name='loader')
    op.drop_index(op.f('ix_loader_role'), table_name='loader')
    op.drop_index(op.f('ix_loader_email'), table_name='loader')
    op.drop_table('loader')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_role'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
