"""empty message

Revision ID: fc4dfc57127e
Revises: 912918f30de6
Create Date: 2019-11-05 12:52:53.743813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4dfc57127e'
down_revision = '912918f30de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loader_role', table_name='loader')
    op.create_index(op.f('ix_loader_role'), 'loader', ['role'], unique=False)
    op.drop_index('ix_recepient_role', table_name='recepient')
    op.create_index(op.f('ix_recepient_role'), 'recepient', ['role'], unique=False)
    op.drop_index('ix_supplier_role', table_name='supplier')
    op.create_index(op.f('ix_supplier_role'), 'supplier', ['role'], unique=False)
    op.drop_index('ix_user_role', table_name='user')
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.create_index('ix_user_role', 'user', ['role'], unique=True)
    op.drop_index(op.f('ix_supplier_role'), table_name='supplier')
    op.create_index('ix_supplier_role', 'supplier', ['role'], unique=True)
    op.drop_index(op.f('ix_recepient_role'), table_name='recepient')
    op.create_index('ix_recepient_role', 'recepient', ['role'], unique=True)
    op.drop_index(op.f('ix_loader_role'), table_name='loader')
    op.create_index('ix_loader_role', 'loader', ['role'], unique=True)
    # ### end Alembic commands ###
